title: Firdaws Aboulaye's Portfolio
author:
  name: Firdaws Aboulaye
  email: aboufred@gmail.com
description: >
  Senior Cloud & Backend Engineer with 10+ years of experience designing and delivering
  scalable backend systems and cloud-native SaaS platforms on AWS. Strong knowledge of
  Kubernetes, serverless architecture, CI/CD, and Infrastructure as Code (Terraform, Helm).
  Proven track record leading projects from conception to production with full observability
  and monitoring. Skilled in backend development with Java, Typescript, and Python.
  Experienced in operating SaaS solutions with a strong focus on reliability, cost-optimization,
  and effective collaboration across SRE, product, and operations teams.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto

  nav_pages:
    - articles.md
    - projects.md

  show_excerpts: false

  social_links:
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/faboulaye"
      icon: linkedin
    - title: "GitHub"
      url: "https://github.com/faboulaye"
      icon: github
