title: Firdaws Aboulaye's Portfolio
author:
  name: Firdaws Aboulaye
  email: aboufred@gmail.com
description: Senior Cloud Engineer

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto

  nav_pages:
    - articles.md
    - projects.md

  show_excerpts: false

  social_links:
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/faboulaye"
      icon: linkedin
    - title: "GitHub"
      url: "https://github.com/faboulaye"
      icon: github

    - title: "Credly"
      url: "https://www.credly.com/users/firdaws-aboulaye"
      icon: credly
